fos_oauth_server:
    db_driver: orm
    client_class:        App\Entity\User\Client
    access_token_class:  App\Entity\User\AccessToken
    refresh_token_class: App\Entity\User\RefreshToken
    auth_code_class:     App\Entity\User\AuthCode
    service:
        user_provider: fos_user.user_provider.username
        options:
          access_token_lifetime: 86400
          refresh_token_lifetime: 1209600
          auth_code_lifetime: 30